// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOXcKU6D106x1-P8jXcvaN9_woY-4Y0Kc',
    appId: '1:291738544922:web:061a15f4bedf799e1a1aa3',
    messagingSenderId: '291738544922',
    projectId: 'designo-5706d',
    authDomain: 'designo-5706d.firebaseapp.com',
    storageBucket: 'designo-5706d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ_cdX0mTF51lDb9YFRwtYxwOSq0NgUlY',
    appId: '1:291738544922:android:f95263ceb03bb3031a1aa3',
    messagingSenderId: '291738544922',
    projectId: 'designo-5706d',
    storageBucket: 'designo-5706d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDJF-sQdpA9f3DTE4snlOdnaa3P7FCUzI',
    appId: '1:291738544922:ios:ed55cbf9a7fc6b401a1aa3',
    messagingSenderId: '291738544922',
    projectId: 'designo-5706d',
    storageBucket: 'designo-5706d.appspot.com',
    iosClientId: '291738544922-ve4bcui97bci0s3b0u0h96beqrsgfpep.apps.googleusercontent.com',
    iosBundleId: 'com.example.devjobs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDJF-sQdpA9f3DTE4snlOdnaa3P7FCUzI',
    appId: '1:291738544922:ios:ed55cbf9a7fc6b401a1aa3',
    messagingSenderId: '291738544922',
    projectId: 'designo-5706d',
    storageBucket: 'designo-5706d.appspot.com',
    iosClientId: '291738544922-ve4bcui97bci0s3b0u0h96beqrsgfpep.apps.googleusercontent.com',
    iosBundleId: 'com.example.devjobs',
  );
}
